# Generated by Django 3.1 on 2020-09-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_recipe_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorite',
        ),
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_by', to='homepage.Recipe'),
        ),
    ]
