# Generated by Django 3.1 on 2020-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200910_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='homepage.Recipe'),
        ),
    ]
